### ISSUE TITLE
run subprocess as a Job in django rq

### ISSUE THREAD

**Issue by faizalprbw** [rq/django-rq#282]
I've been trying to run python file by using subprocess inside job like this :
```
@job('high')
def run_program(value):
    path_to_file = '/home/dir1/program.py'
    subprocess.call(['sudo', 'python', path_to_file, '--parameter', value])
```
then the job is failed and  i got this error:
```
Traceback (most recent call last):
  File "/home/vagrant/.virtualenvs/otoklim/local/lib/python2.7/site-packages/rq/worker.py", line 789, in perform_job
    rv = job.perform()
  File "/home/vagrant/.virtualenvs/otoklim/local/lib/python2.7/site-packages/rq/job.py", line 573, in perform
    self._result = self._execute()
  File "/home/vagrant/.virtualenvs/otoklim/local/lib/python2.7/site-packages/rq/job.py", line 579, in _execute
    return self.func(*self.args, **self.kwargs)
  File "/home/vagrant/otoklim/otoklim/otoklim/tasks.py", line 105, in run_otoklim
    subprocess.call(['sudo', 'python', path_to_file, '--parameter', value])
  File "/usr/lib/python2.7/subprocess.py", line 523, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```
i'm sure that the file is exists and it will be work if i run it without using django rq..
I also has try to run something like this..
`subprocess.call('sudo python /home/dir1/program.py --parameter value', shell=True)`
The job is finished but the program seems like not working at all. The expected result is not created..

Is there any way to run python file `sudo python program.py` by using django rq?

**Comment by selwin** [comment]
This is not an issue with DjangoRQ itself. The stack trace you provided indicates that it python was unable to find the file you specified.

**Comment by faizalprbw** [comment]
could you please try to run subprocess by using django-rq..? When i try to run it without django-rq, it's works..
