### ISSUE TITLE
RecursionError: maximum recursion depth exceeded (urls.py and Django 2.0.4)

### ISSUE THREAD

**Issue by richardgiddings** [rq/django-rq#287]
When I include the following in my application urls.py
```
# For Django >= 2.0
urlpatterns += [
    url(r'^django-rq/', (urlpatterns, '', 'django_rq'))
]
```
I get the following error when running 'python manage.py runserver':
```
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x1033c89d8>
Traceback (most recent call last):
  File "/Users/richardgiddings/django/code/nicethingshappen/lib/python3.5/site-packages/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/Users/richardgiddings/django/code/nicethingshappen/lib/python3.5/site-packages/django/core/management/commands/runserver.py", line 120, in inner_run
    self.check(display_num_errors=True)
  File "/Users/richardgiddings/django/code/nicethingshappen/lib/python3.5/site-packages/django/core/management/base.py", line 364, in check
    include_deployment_checks=include_deployment_checks,
  File "/Users/richardgiddings/django/code/nicethingshappen/lib/python3.5/site-packages/django/core/management/base.py", line 351, in _run_checks
    return checks.run_checks(**kwargs)
  File "/Users/richardgiddings/django/code/nicethingshappen/lib/python3.5/site-packages/django/core/checks/registry.py", line 73, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/Users/richardgiddings/django/code/nicethingshappen/lib/python3.5/site-packages/django/core/checks/urls.py", line 40, in check_url_namespaces_unique
    all_namespaces = _load_all_namespaces(resolver)
  File "/Users/richardgiddings/django/code/nicethingshappen/lib/python3.5/site-packages/django/core/checks/urls.py", line 67, in _load_all_namespaces
.
.
.
  File "/Users/richardgiddings/django/code/nicethingshappen/lib/python3.5/site-packages/django/core/checks/urls.py", line 59, in _load_all_namespaces
    ':'.join(parents + (url.namespace,)) for url in url_patterns
RecursionError: maximum recursion depth exceeded
```

Is there something obvious I have done wrong?

Also can we use path() rather than url()? Something like:
`path('django-rq/', include('django_rq.urls'))`

**Comment by richardgiddings** [comment]
Works putting the following in app urls.py with Django 2.0.4: 
`path('django-rq/', include('django_rq.urls'))`
