### ISSUE TITLE
ModuleNotFoundError: No module named 'django-rq'

### ISSUE THREAD

**Issue by erikdao** [rq/django-rq#289]
I couldn't get the latest `django-rq` to run with my `django` setup. I'm using `django==2.0.4` with `pipevn`, when I tried to run the development server, it said:

```
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x10645bd08>
Traceback (most recent call last):
  File "/Users/username/.local/share/virtualenvs/project_x-5muY3MWa/lib/python3.6/site-packages/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/Users/username/.local/share/virtualenvs/project_x-5muY3MWa/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 112, in inner_run
    autoreload.raise_last_exception()
  File "/Users/username/.local/share/virtualenvs/project_x-5muY3MWa/lib/python3.6/site-packages/django/utils/autoreload.py", line 248, in raise_last_exception
    raise _exception[1]
  File "/Users/username/.local/share/virtualenvs/project_x-5muY3MWa/lib/python3.6/site-packages/django/core/management/__init__.py", line 327, in execute
    autoreload.check_errors(django.setup)()
  File "/Users/username/.local/share/virtualenvs/project_x-5muY3MWa/lib/python3.6/site-packages/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/Users/username/.local/share/virtualenvs/project_x-5muY3MWa/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/username/.local/share/virtualenvs/project_x-5muY3MWa/lib/python3.6/site-packages/django/apps/registry.py", line 89, in populate
    app_config = AppConfig.create(entry)
  File "/Users/username/.local/share/virtualenvs/project_x-5muY3MWa/lib/python3.6/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/Users/username/.local/share/virtualenvs/project_x-5muY3MWa/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'django-rq'
```

Here is my `django-rq` info:

```
Name: django-rq
Version: 1.1.0
Summary: An app that provides django integration for RQ (Redis Queue)
Home-page: https://github.com/ui/django-rq
Author: Selwin Ong
Author-email: selwin.ong@gmail.com
License: MIT
Location: /Users/username/.local/share/virtualenvs/project_x-5muY3MWa/lib/python3.6/site-packages
Requires: rq, django
Required-by:
```

Does anyone encounter this error?

**Comment by erikdao** [comment]
It turns out that it was due to my typo in `INSTALLED_APPS`, I used `django-rq` instead of `django_rq`
