### ISSUE TITLE
django-rq not working for jobs that use multiprocess.Pool

### ISSUE THREAD

**Issue by nguyenhuyanhh** [rq/django-rq#305]
I have a job that is internally using `multiprocess.Pool` and it's not running in django-rq. I try another job which does not use `Pool` and it runs so there should not be any problem with django-rq.

Is my assumption correct? Attaching the job and the logs for your reference:

```
@job('vista')
def run_operation(operation_id):
    obj = Operation.objects.get(id=operation_id)
    result = obj._sync_run()
    obj.result = json.dumps(result)
    obj.save()
```

```
[03/Nov/2018 18:02:25] [INFO:worker(523):19741] vista: demo.apis.run_operation(24) (3e45f3fc-ecc6-42fd-9885-efa0b9fc560a)
[03/Nov/2018 18:02:25] [DEBUG:worker(548):19741] Sent heartbeat to prevent worker timeout. Next one should arrive within 420 seconds.
[03/Nov/2018 18:02:25] [DEBUG:worker(548):20070] Sent heartbeat to prevent worker timeout. Next one should arrive within 35 seconds.
[03/Nov/2018 18:02:35] [ERROR:worker(839):20070] rq.timeouts.JobTimeoutException: Task exceeded maximum timeout value (10 seconds)
Traceback (most recent call last):
  File "/home/nhanh/graymatics/gmtc-vista/.venv/lib/python3.6/site-packages/rq/worker.py", line 793, in perform_job
    rv = job.perform()
  File "/home/nhanh/graymatics/gmtc-vista/.venv/lib/python3.6/site-packages/rq/job.py", line 599, in perform
    self._result = self._execute()
  File "/home/nhanh/graymatics/gmtc-vista/.venv/lib/python3.6/site-packages/rq/job.py", line 605, in _execute
    return self.func(*self.args, **self.kwargs)
  File "/home/nhanh/graymatics/gmtc-vista/demo/apis.py", line 143, in run_operation
    result = obj._sync_run()
  File "/home/nhanh/graymatics/gmtc-vista/demo/models.py", line 568, in _sync_run
    return self.upload.run(self._subscriptions_list, self.user.is_staff)
  File "/home/nhanh/graymatics/gmtc-vista/demo/models.py", line 475, in run
    result_list = self.pool.map(_run_single, subscription_list)
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 638, in get
    self.wait(timeout)
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 635, in wait
    self._event.wait(timeout)
  File "/usr/lib/python3.6/threading.py", line 551, in wait
    signaled = self._cond.wait(timeout)
  File "/usr/lib/python3.6/threading.py", line 295, in wait
    waiter.acquire()
  File "/home/nhanh/graymatics/gmtc-vista/.venv/lib/python3.6/site-packages/rq/timeouts.py", line 64, in handle_death_penalty
    '({0} seconds)'.format(self._timeout))
rq.timeouts.JobTimeoutException: Task exceeded maximum timeout value (10 seconds)
Traceback (most recent call last):
  File "/home/nhanh/graymatics/gmtc-vista/.venv/lib/python3.6/site-packages/rq/worker.py", line 793, in perform_job
    rv = job.perform()
  File "/home/nhanh/graymatics/gmtc-vista/.venv/lib/python3.6/site-packages/rq/job.py", line 599, in perform
    self._result = self._execute()
  File "/home/nhanh/graymatics/gmtc-vista/.venv/lib/python3.6/site-packages/rq/job.py", line 605, in _execute
    return self.func(*self.args, **self.kwargs)
  File "/home/nhanh/graymatics/gmtc-vista/demo/apis.py", line 143, in run_operation
    result = obj._sync_run()
  File "/home/nhanh/graymatics/gmtc-vista/demo/models.py", line 568, in _sync_run
    return self.upload.run(self._subscriptions_list, self.user.is_staff)
  File "/home/nhanh/graymatics/gmtc-vista/demo/models.py", line 475, in run
    result_list = self.pool.map(_run_single, subscription_list)
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 638, in get
    self.wait(timeout)
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 635, in wait
    self._event.wait(timeout)
  File "/usr/lib/python3.6/threading.py", line 551, in wait
    signaled = self._cond.wait(timeout)
  File "/usr/lib/python3.6/threading.py", line 295, in wait
    waiter.acquire()
  File "/home/nhanh/graymatics/gmtc-vista/.venv/lib/python3.6/site-packages/rq/timeouts.py", line 64, in handle_death_penalty
    '({0} seconds)'.format(self._timeout))
rq.timeouts.JobTimeoutException: Task exceeded maximum timeout value (10 seconds)
[03/Nov/2018 18:02:35] [DEBUG:worker(843):20070] Invoking exception handler <bound method Worker.move_to_failed_queue of <rq.worker.Worker object at 0x7fed54604710>>
[03/Nov/2018 18:02:35] [WARNING:worker(856):20070] Moving job to 'failed' queue
```

Thanks a lot!

**Comment by james4388** [comment]
I think worker already on a thread, it cannot spawn a process? Can U use thread pool?

**Comment by nguyenhuyanhh** [comment]
@james4388 I think that is the issue, but cannot confirm. Anyway I found a workaround, instead of calling the function directly, I call it indirectly through an API request, seems to work fine.
