### ISSUE TITLE
haystack update_index as periodic job

### ISSUE THREAD

**Issue by lucas03** [rq/django-rq#318]
I want to update search index daily, I think I tested it in the past on localhost and it worked, but not sure. 

Basically, this is in my cron job I schedule:
```
    dict(
        cron_string="30 3 * * *",
        func=management.call_command,
        args=["update_index --workers=4 --remove"],
        kwargs={},
        repeat=None,
        queue_name="default",
        timeout=1000,
    ),
```
but this call ends with error in django_rq admin page:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 102, in call_command
    app_name = get_commands()[command_name]
KeyError: 'update_index --workers=4 --remove'


During handling of the above exception, another exception occurred:


Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/rq/worker.py", line 793, in perform_job
    rv = job.perform()
  File "/usr/local/lib/python3.6/site-packages/rq/job.py", line 599, in perform
    self._result = self._execute()
  File "/usr/local/lib/python3.6/site-packages/rq/job.py", line 605, in _execute
    return self.func(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 104, in call_command
    raise CommandError("Unknown command: %r" % command_name)
django.core.management.base.CommandError: Unknown command: 'update_index --workers=4 --remove'
```

Anybody has an idea what I might be doing wrong?

**Comment by selwin** [comment]
This is not a django-rq related question.
