### ISSUE TITLE
django-rq don't load Django Enviroment settings

### ISSUE THREAD

**Issue by l2radamanthys** [rq/django-rq#418]
When I try to run a job in server django-rq don't load django enviroment settings

```
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.6/site-packages/rq/worker.py", line 884, in perform_job
    rv = job.perform()
  File "/app/.heroku/python/lib/python3.6/site-packages/rq/job.py", line 664, in perform
    self._result = self._execute()
  File "/app/.heroku/python/lib/python3.6/site-packages/rq/job.py", line 670, in _execute
    return self.func(*self.args, **self.kwargs)
  File "/app/.heroku/python/lib/python3.6/site-packages/rq/job.py", line 215, in func
    return import_attribute(self.func_name)
  File "/app/.heroku/python/lib/python3.6/site-packages/rq/utils.py", line 152, in import_attribute
    module = importlib.import_module(module_name)
  File "/app/.heroku/python/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'app.trabajos.pdf_seven_day_notification'
```

**Comment by selwin** [comment]
You should run the worker using Django's management command; i.e `./manage.py rqworker`
