### ISSUE TITLE
RQ 1.4.0 breaks django_rq

### ISSUE THREAD

**Issue by dglinyanov** [rq/django-rq#423]
When rq version is not fixed in requirements (`django-rq==2.3.1` - this is in requirements):
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/template/backends/django.py", line 121, in get_package_libraries
    module = import_module(entry[1])
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.8/site-packages/django_rq/templatetags/django_rq.py", line 4, in <module>
    from rq.exceptions import UnpickleError
ImportError: cannot import name 'UnpickleError' from 'rq.exceptions' (/usr/local/lib/python3.8/site-packages/rq/exceptions.py)
```

Manually adding `rq==1.3.0` (latest that worked) fixes problem.

**Comment by dglinyanov** [comment]
Sorry, didn't search closed issues.
