### ISSUE TITLE
ValueError: unsupported pickle protocol: 5

### ISSUE THREAD

**Issue by taewookim** [rq/django-rq#472]
OS: Ubuntu 20.04 LTS
Python 3.7.5
Django RQ: 2.4.0
RQ scheduler:  (not sure, installed via pip, so should be latest stable)
Redis Server v=5.0.5 

> Traceback (most recent call last):
>   File "manage.py", line 22, in <module>
>     execute_from_command_line(sys.argv)
>   File "/home/django/lib/python3.7/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
>     utility.execute()
>   File "/home/django/lib/python3.7/site-packages/django/core/management/__init__.py", line 395, in execute
>     self.fetch_command(subcommand).run_from_argv(self.argv)
>   File "/home/django/lib/python3.7/site-packages/django/core/management/base.py", line 330, in run_from_argv
>     self.execute(*args, **cmd_options)
>   File "/home/django/lib/python3.7/site-packages/django/core/management/base.py", line 371, in execute
>     output = self.handle(*args, **options)
>   File "/home/django/leadautomation/gentelella/app/management/commands/redis_view_queue.py", line 36, in handle
>     dupe_found = self.count_jobs(ignore_keys=["cron_string"])
>   File "/home/django/leadautomation/gentelella/app/management/commands/redis_view_queue.py", line 95, in count_jobs
>     for job in scheduler.get_jobs():
>   File "/home/django/lib/python3.7/site-packages/rq_scheduler/scheduler.py", line 352, in get_jobs
>     job = self.job_class.fetch(job_id, connection=self.connection)
>   File "/home/django/lib/python3.7/site-packages/rq/job.py", line 307, in fetch
>     job.refresh()
>   File "/home/django/lib/python3.7/site-packages/rq/job.py", line 538, in refresh
>     self.restore(data)
>   File "/home/django/lib/python3.7/site-packages/rq/job.py", line 514, in restore
>     self.meta = self.serializer.loads(obj.get('meta')) if obj.get('meta') else {}
> ValueError: unsupported pickle protocol: 5
> 

Could this be a pickle version?

print(pickle.format_version) => 4.0

**Comment by taewookim** [comment]
[This helped](https://github.com/rq/rq/issues/598#issuecomment-160152546)
If anyone's having this issue, i put the code in settings.py

**Comment by taewookim** [comment]
ANy ideas?
