### ISSUE TITLE
keys of command in MULTI calls must be in same slot

### ISSUE THREAD

**Issue by TracyRAN1** [rq/django-rq#648]
`16:48:55 [Job 513a1850-bc5b-4ed4-9df5-e7991bb93c6d]: exception raised while executing (apps.sms.tasks.send_work_message)
Traceback (most recent call last):
  File "/xinshi-app/venv/lib/python3.10/site-packages/rq/worker.py", line 1440, in perform_job
    self.handle_job_success(job=job, queue=queue, started_job_registry=started_job_registry)
  File "/xinshi-app/venv/lib/python3.10/site-packages/rq/worker.py", line 1399, in handle_job_success
    pipeline.execute()
  File "/xinshi-app/venv/lib/python3.10/site-packages/redis/client.py", line 1478, in execute
    return conn.retry.call_with_retry(
  File "/xinshi-app/venv/lib/python3.10/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
  File "/xinshi-app/venv/lib/python3.10/site-packages/redis/client.py", line 1479, in <lambda>
    lambda: execute(conn, stack, raise_on_error),
  File "/xinshi-app/venv/lib/python3.10/site-packages/redis/client.py", line 1348, in _execute_transaction
    response = self.parse_response(connection, "_")
  File "/xinshi-app/venv/lib/python3.10/site-packages/redis/client.py", line 1416, in parse_response
    result = Redis.parse_response(self, connection, command_name, **options)
  File "/xinshi-app/venv/lib/python3.10/site-packages/redis/client.py", line 553, in parse_response
    response = connection.read_response()
  File "/xinshi-app/venv/lib/python3.10/site-packages/redis/connection.py", line 524, in read_response
    raise response
redis.exceptions.ResponseError: keys of command in MULTI calls must be in same slot`

how can i fix this problem?

**Comment by TracyRAN1** [comment]
djang-rq not support redis cluster?
